### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by itheodoridis** [h4ndzdatm0ld/nornir_netconf#21]
Hello, while trying to install on venv with python 3.10.1 for ubuntu 20.04.3 I get the error:
`ERROR: Could not find a version that satisfies the requirement nornir_netconf (from versions: none)
ERROR: No matching distribution found for nornir_netconf
`
The same installation works with a venv based on python3.8

**Comment by h4ndzdatm0ld** [comment]
Hi @itheodoridis   Apologize, I completely did not see this. I spent a little time today and monkeyed with the dependencies and loosened the python requirements as well as updating the CI to ensure 3.7-10 work. Let me know if this clears it up. Thanks for checking this project out!

**Comment by itheodoridis** [comment]
Hey ! Sorry I missed your response!! That's actually great news for me as I have a project in the works! Thank you so much for your efforts!

**Comment by h4ndzdatm0ld** [comment]
@itheodoridis Gotcha! I just released a new version, dropped ncclient to hopefully help with this. Took the time to run some integration testing with containerlab, so it's a win win! Thanks, let me know it works and any future feedback is super appreciated!

**Comment by itheodoridis** [comment]
Great!! Containerlab is great, I haven't found the time to try it yet. I will keep you up to date.

**Comment by itheodoridis** [comment]
installation succeeded without errors with nornir-netconf 1.0.1! I will keep you posted about the project in slack.
Thanks again!
