### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by bacala** [h4ndzdatm0ld/nornir_netconf#73]
Hi,

I saw, you have the new bare bone rpc task already added to the develop. Could you release a new version 2.1.0 for example, so it we can use this new valuable task?

Thanks for any feedback. If you need help I could contribute for it.
BR
Bacala

**Comment by maercu** [comment]
@h4ndzdatm0ld 
Same here, could you please update the version.

Thank you very much
Marcel

**Comment by h4ndzdatm0ld** [comment]
Sorry for lack of coms here. I will release a new ver

**Comment by h4ndzdatm0ld** [comment]
Released

**Comment by maercu** [comment]
Thank you very much, @h4ndzdatm0ld
